# Generated by Django 4.1 on 2023-02-11 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_copmment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Copmment',
            new_name='Comment',
        ),
    ]
